#!/bin/bash

usage () {
  echo "usage: jobs [OPTIONS] (to|from) AIRPORT"
  echo " OPTIONS"
  echo "  -f FMT   output format. FMT is either 'CSV', 'COL', or 'TAB'. By default,"
  echo "           it will output in COL format if printing to a terminal and"
  echo "           CSV format otherwise."
  echo " AIRPORT must be ICAO code."
  exit
}

if (( $# < 2 )); then
  usage
fi

while getopts ":hf:" opt; do
  case "$opt" in
    f)
      case "${OPTARG^^}" in
        CSV) fmt="csv" ;;
        COL) fmt="col" ;;
        TAB) fmt="tab" ;;
        *) echo "Invalid argument for -f. Must use 'COL' or 'CSV'"; usage ;;
      esac ;;
    *) usage ;;
  esac
done

shift $((OPTIND - 1))

case "${1^^}" in
  TO) direction="to" ;;
  FROM) direction="from" ;;
  *) usage ;;
esac
shift

icao="${1^^}"
shift

libdir="${BASH_SOURCE%/*}/lib"
datadir="${BASH_SOURCE%/*}/cache"
data="$datadir/seats-$direction-$icao.csv"
"$libdir"/fetch_apt "$direction" "$icao" || exit
icaodata="$datadir/icaodata.csv"
source "$libdir/fselib.sh"

export direction minseats icaodata

printf "From %s\n" "$icao"
awk -f "$libdir/jobs.awk" "$data" | output_formatter
