#!/bin/bash

usage () {
  echo "usage: seats OPTIONS (to|from) AIRPORT"
  echo " OPTIONS"
  echo "  -m MIN   minimum seats"
  echo " AIRPORT must be ICAO code."
  exit
}

if (( $# < 2 )); then
  usage
fi

# Set defaults
: ${minseats:=1}

while getopts ":m:" opt; do
  case "$opt" in
    m) minseats="$OPTARG" ;;
  esac
done

shift $((OPTIND - 1))

case "${1^^}" in
  TO) direction="to" ;;
  FROM) direction="from" ;;
  *) usage ;;
esac
shift

icao="${1^^}"
shift

libdir="${BASH_SOURCE%/*}/lib"
datadir="${BASH_SOURCE%/*}/cache"
data="$datadir/seats-$direction-$icao.csv"
"$libdir"/fetch_apt "$direction" "$icao" || exit
icaodata="$datadir/icaodata.csv"

export direction minseats icaodata

printf "Seats From %s\n" "$icao"
awk -f "$libdir/seats.awk" "$data" | column -t -s'	'
